export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const SUBMIT_FILE = 'SUBMIT_FILE'
export const UPDATE_DOC='UPDATE_DOC'
export const SETDATA='SETDATA'
export const RESET = 'RESET'
export const HANDLE_ERROR = 'HANDLE_ERROR'