export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const SUBMIT_FILE = 'SUBMIT_FILE'
export const HANDLE_UPDATE = 'HANDLE_UPDATE'
export const UPDATE_DOC='UPDATE_DOC'
export const HANDLE_SUBMIT = 'HANDLE_SUBMIT'
export const SETDATA='SETDATA'
export const RESET = 'RESET'